apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: awx
  namespace: awx
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`awx.gpu02.lysdemolab.fr`)
    middlewares:
#    - name: security
#    - name: ratelimit
    services:
    - name: awx-demo-service
      port: 80
  tls:
    certResolver: letsencrypt
